config/routes.rb
Rails.application.routes.draw do
  resources :songs, only: [:create, :index]
  resource :upvote, only: [:create, :destroy]

  root "songs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all.order(votes: :desc, title: :asc)
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    @song.votes = 1

    if @song.url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      @song.url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end
    @song.url = "http://www.youtube.com/embed/#{ youtube_id }"

    respond_to do |format|
      if @song.save
        format.html { redirect_to root_path, notice: 'Song was successfully added. Thank you!' }
      else
        format.html { redirect_to root_path }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :artist, :url, :suggested_by, :votes)
    end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  before_action :set_song, only: [:create, :destroy]

  # POST /songs
  # POST /songs.json
  def create
    @song.votes = @song.votes + 1

    respond_to do |format|
      if @song.save
        format.html { redirect_to songs_path, notice: "You just upvoted #{@song.title}!" }
      else
        format.html { render songs_path }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.votes = @song.votes - 1
    respond_to do |format|
      if @song.save
        format.html { redirect_to songs_path, notice: "You just downvoted #{@song.title}!" }
      else
        format.html { redirect_to songs_path }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :artist, :url, :suggested_by, :votes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def youtube_video(url)
    render :partial => 'shared/video', :locals => { :url => url }
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wedding
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_video.html.haml
%iframe{:id => "mainVideo", :allowfullscreen => "", :frameborder => "0", :height => "300px", :src => url, :width => "100%"}

app/views/songs/_form.html.haml
= simple_form_for song, html: { class: 'form-inline' } do |form|
  - if song.errors.any?
    #error_explanation
      %h2
        = pluralize(song.errors.count, "error")
        prohibited this song from being saved:
      %ul
        - song.errors.full_messages.each do |message|
          %li= message

  = form.input :title, label_html: { class: 'mx-2' }
  = form.input :artist, label_html: { class: 'mx-2' }
  = form.input :url, placeholder: 'youtube.com...', label_html: { class: 'mx-2' }
  = form.input :suggested_by, label_html: { class: 'mx-2' }

  = form.button :submit, 'Add Song', class: 'btn btn-primary mx-2'

app/views/songs/_song.html.haml
.m-3
  %a.list-group-item.list-group-item-action.flex-column.align-items-start{:href => song.url, :target => '_blank'}
    .d-flex.w-100.justify-content-between
      %h5.mb-1= song.title
      %h5.badge.badge-primary.badge-pill= song.votes
    .d-flex.w-100.justify-content-between
      %p.mb-1= song.artist
    %small="Suggested by #{song.suggested_by}"

  .d-flex.w-100.justify-content-between
    = link_to 'Upvote', upvote_path(id: song.id), method: :post, class: 'btn btn-primary'
    = link_to 'Downvote', upvote_path(id: song.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

    = button_tag 'Play', type: 'button', onclick: "swapYoutube(\'#{song.url}\')", class: 'btn btn-secondary'

app/views/songs/edit.html.haml
%h1 Editing Song
= render 'form', song: @song
= link_to 'Show', @song
|
= link_to 'Back', songs_path

app/views/songs/index.html.haml
%p#notice= notice
.text-center
  %h1 Katherine & Nicholas
  %p Wedding Music Suggestions
%p
  =render partial: 'form', locals: { song: Song.new }

.test
  = youtube_video @songs.first.url

.scrollable
  .list-group
    =render @songs

app/views/songs/new.html.haml
%h1 New Song
= render 'form', song: @song
= link_to 'Back', songs_path

app/views/songs/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @song.title
%p
  %strong Artist:
  = @song.artist
%p
  %strong Url:
  = @song.url
%p
  %strong Suggested by:
  = @song.suggested_by
%p
  %strong Votes:
  = @song.votes
= link_to 'Edit', edit_song_path(@song)
|
= link_to 'Back', songs_path